<?php

namespace App\Filament\Pages\Auth;
 use Filament\Facades\Filament;
 use Filament\Forms\Form;
 use Filament\Pages\Auth\Login as BaseLogin;
class Login extends BaseLogin
{

    public function mount(): void
    {
        if (Filament::auth()->check()) {
            redirect()->intended(Filament::getUrl());
        }

        $this->form->fill();
    }

    public function form(Form $form): Form
    {
        return parent::form($form); // TODO: Change the autogenerated stub
    }

}
